### ISSUE TITLE
加入的usb3和sip驱动真的能生效吗？

### ISSUE THREAD

**Issue by FanFansfan** [Izumiko/uboot-beikeyun#1]
看到patch里面的usb3似乎是内核驱动复制过来的，故有此疑问，他们真的能生效吗？

**Comment by Izumiko** [comment]
由于我的dts是直接用的内核那里面的，所以只是把编译uboot时提示缺少的文件加了进去。估计大概率没生效，目前只是能把系统引导起来

**Comment by FanFansfan** [comment]
感谢，搜了下rk3399的uboot usb3 patch，这里直接用内核驱动应该是不行的。
